In [1]:
import pandas as pd
import bionlp

In [ ]:
df = pd.read_excel('Pediatric Oncology Drug Approvals  FDA.xlsx', header=1)

In [4]:
df[0:5]

,DRUGS APPROVED FOR PEDIATRIC CANCERS [BRAND NAME] 1,INDICATION 2,PEDIATRIC APPROVAL DATE 3*
0,Revumenib [Revuforj],Treatment of relapsed or refractory acute leuk...,11-15-2024
1,Vorasidenib [Voranigo],Treatment of adult and pediatric patients 12 y...,08-06-2024
2,Blinatumomab [Blincyto],Treatment of CD19-positive Philadelphia chromo...,06-14-2024
3,Repotrectinib [Augtyro],Treatment of adult and pediatric patients 12 y...,06-13-2024
4,Selpercatinib [Retevmo],Treatment of adult and pediatric patients 2 ye...,05-29-2024

In [4]:
df['INDICATION 2'][0:90]

0     Treatment of relapsed or refractory acute leuk...
1     Treatment of adult and pediatric patients 12 y...
2     Treatment of CD19-positive Philadelphia chromo...
3     Treatment of adult and pediatric patients 12 y...
4     Treatment of adult and pediatric patients 2 ye...
                            ...
85    Prophylaxis and treatment of meningeal leukemi...
86    Treatment of adults and pediatric patients wit...
87    Treatment of adults and pediatric patients wit...
88    Treatment of adult and pediatric patients with...
89    Remission induction and remission consolidatio...
Name: INDICATION 2, Length: 90, dtype: object

In [5]:
# results = bionlp.process_text(df['indications_and_usage'][2])
results = bionlp.batch(df['INDICATION 2'][0:90])

249it [00:44,  5.66it/s]

In [6]:
results

,entity_group,score,word,start,end,original_text,concept_match_type,concept_id,concept_label
0,GENETIC,0.999995,lysine methyltransferase 2A gene,58.0,90.0,Treatment of relapsed or refractory acute leuk...,0,None,None
1,GENETIC,0.999970,KMT2A,92.0,97.0,Treatment of relapsed or refractory acute leuk...,100,normalize.gene.hgnc:7132,KMT2A
2,CHEMICAL,0.999998,lysine,58.0,64.0,Treatment of relapsed or refractory acute leuk...,80,normalize.therapy.rxcui:6536,lysine
3,DISEASE,0.999987,acute leukemia,36.0,50.0,Treatment of relapsed or refractory acute leuk...,80,normalize.disease.ncit:C9300,Acute Leukemia
4,GENETIC,0.999995,isocitrate dehydrogenase - 1,126.0,152.0,Treatment of adult and pediatric patients 12 y...,0,None,None
...,...,...,...,...,...,...,...,...,...
244,DISEASE,0.999989,Non - Hodgkin lymphoma,48.0,68.0,Treatment of adults and pediatric patients wit...,0,None,None
245,DISEASE,0.999993,osteosarcoma,48.0,60.0,Treatment of adults and pediatric patients wit...,80,normalize.disease.ncit:C9145,Osteosarcoma
246,DISEASE,0.999992,acute lymphoblastic leukemia,47.0,75.0,Treatment of adult and pediatric patients with...,80,normalize.disease.ncit:C3167,Acute Lymphoblastic Leukemia
247,DISEASE,0.999993,ALL,77.0,80.0,Treatment of adult and pediatric patients with...,60,normalize.disease.ncit:C3167,Acute Lymphoblastic Leukemia
248,DISEASE,0.999991,acute nonlymphocytic leukemias,61.0,91.0,Remission induction and remission consolidatio...,60,normalize.disease.ncit:C3171,Acute Myeloid Leukemia

In [7]:
results[results['concept_match_type']!=0].reset_index(drop=True)

,entity_group,score,word,start,end,original_text,concept_match_type,concept_id,concept_label
0,GENETIC,0.999970,KMT2A,92.0,97.0,Treatment of relapsed or refractory acute leuk...,100,normalize.gene.hgnc:7132,KMT2A
1,CHEMICAL,0.999998,lysine,58.0,64.0,Treatment of relapsed or refractory acute leuk...,80,normalize.therapy.rxcui:6536,lysine
2,DISEASE,0.999987,acute leukemia,36.0,50.0,Treatment of relapsed or refractory acute leuk...,80,normalize.disease.ncit:C9300,Acute Leukemia
3,GENETIC,0.999984,IDH1,154.0,158.0,Treatment of adult and pediatric patients 12 y...,100,normalize.gene.hgnc:5382,IDH1
4,GENETIC,0.999985,IDH2,191.0,195.0,Treatment of adult and pediatric patients 12 y...,100,normalize.gene.hgnc:5383,IDH2
...,...,...,...,...,...,...,...,...,...
177,DISEASE,0.999832,meningeal leukemia,29.0,47.0,Prophylaxis and treatment of meningeal leukemi...,80,normalize.disease.ncit:C94754,Meningeal Leukemia
178,DISEASE,0.999993,osteosarcoma,48.0,60.0,Treatment of adults and pediatric patients wit...,80,normalize.disease.ncit:C9145,Osteosarcoma
179,DISEASE,0.999992,acute lymphoblastic leukemia,47.0,75.0,Treatment of adult and pediatric patients with...,80,normalize.disease.ncit:C3167,Acute Lymphoblastic Leukemia
180,DISEASE,0.999993,ALL,77.0,80.0,Treatment of adult and pediatric patients with...,60,normalize.disease.ncit:C3167,Acute Lymphoblastic Leukemia
181,DISEASE,0.999991,acute nonlymphocytic leukemias,61.0,91.0,Remission induction and remission consolidatio...,60,normalize.disease.ncit:C3171,Acute Myeloid Leukemia

In [8]:
results['FDA Brand Label'] = None
for idx,row in results.iterrows():
    tdf = df[df['INDICATION 2']==row['original_text']].reset_index(drop=True)
    results.at[idx, 'FDA Brand Label'] = tdf['DRUGS APPROVED FOR PEDIATRIC CANCERS [BRAND NAME] 1'][0]

results

,entity_group,score,word,start,end,original_text,concept_match_type,concept_id,concept_label,FDA Brand Label
0,GENETIC,0.999995,lysine methyltransferase 2A gene,58.0,90.0,Treatment of relapsed or refractory acute leuk...,0,None,None,Revumenib [Revuforj]
1,GENETIC,0.999970,KMT2A,92.0,97.0,Treatment of relapsed or refractory acute leuk...,100,normalize.gene.hgnc:7132,KMT2A,Revumenib [Revuforj]
2,CHEMICAL,0.999998,lysine,58.0,64.0,Treatment of relapsed or refractory acute leuk...,80,normalize.therapy.rxcui:6536,lysine,Revumenib [Revuforj]
3,DISEASE,0.999987,acute leukemia,36.0,50.0,Treatment of relapsed or refractory acute leuk...,80,normalize.disease.ncit:C9300,Acute Leukemia,Revumenib [Revuforj]
4,GENETIC,0.999995,isocitrate dehydrogenase - 1,126.0,152.0,Treatment of adult and pediatric patients 12 y...,0,None,None,Vorasidenib [Voranigo]
...,...,...,...,...,...,...,...,...,...,...
244,DISEASE,0.999989,Non - Hodgkin lymphoma,48.0,68.0,Treatment of adults and pediatric patients wit...,0,None,None,Methotrexate
245,DISEASE,0.999993,osteosarcoma,48.0,60.0,Treatment of adults and pediatric patients wit...,80,normalize.disease.ncit:C9145,Osteosarcoma,Methotrexate
246,DISEASE,0.999992,acute lymphoblastic leukemia,47.0,75.0,Treatment of adult and pediatric patients with...,80,normalize.disease.ncit:C3167,Acute Lymphoblastic Leukemia,Mercaptopurine [Purinethol tablet] &
247,DISEASE,0.999993,ALL,77.0,80.0,Treatment of adult and pediatric patients with...,60,normalize.disease.ncit:C3167,Acute Lymphoblastic Leukemia,Mercaptopurine [Purinethol tablet] &
248,DISEASE,0.999991,acute nonlymphocytic leukemias,61.0,91.0,Remission induction and remission consolidatio...,60,normalize.disease.ncit:C3171,Acute Myeloid Leukemia,Thioguanine [Tabloid]

In [9]:
tdf = results[results['concept_match_type']!=0].reset_index(drop=True)
tdf[tdf['entity_group']=='DISEASE']['FDA Brand Label'].nunique()

57

In [10]:
# tdf.to_excel('tagged-dataset.xlsx')

In [10]:
tdf[(tdf['entity_group']=='GENETIC') | (tdf['entity_group']=='DISEASE')].reset_index(drop=True)

,entity_group,score,word,start,end,original_text,concept_match_type,concept_id,concept_label,FDA Brand Label
0,GENETIC,0.999970,KMT2A,92.0,97.0,Treatment of relapsed or refractory acute leuk...,100,normalize.gene.hgnc:7132,KMT2A,Revumenib [Revuforj]
1,DISEASE,0.999987,acute leukemia,36.0,50.0,Treatment of relapsed or refractory acute leuk...,80,normalize.disease.ncit:C9300,Acute Leukemia,Revumenib [Revuforj]
2,GENETIC,0.999984,IDH1,154.0,158.0,Treatment of adult and pediatric patients 12 y...,100,normalize.gene.hgnc:5382,IDH1,Vorasidenib [Voranigo]
3,GENETIC,0.999985,IDH2,191.0,195.0,Treatment of adult and pediatric patients 12 y...,100,normalize.gene.hgnc:5383,IDH2,Vorasidenib [Voranigo]
4,DISEASE,0.999994,astrocytoma,74.0,85.0,Treatment of adult and pediatric patients 12 y...,80,normalize.disease.ncit:C60781,Astrocytoma,Vorasidenib [Voranigo]
...,...,...,...,...,...,...,...,...,...,...
146,DISEASE,0.999832,meningeal leukemia,29.0,47.0,Prophylaxis and treatment of meningeal leukemi...,80,normalize.disease.ncit:C94754,Meningeal Leukemia,Methotrexate
147,DISEASE,0.999993,osteosarcoma,48.0,60.0,Treatment of adults and pediatric patients wit...,80,normalize.disease.ncit:C9145,Osteosarcoma,Methotrexate
148,DISEASE,0.999992,acute lymphoblastic leukemia,47.0,75.0,Treatment of adult and pediatric patients with...,80,normalize.disease.ncit:C3167,Acute Lymphoblastic Leukemia,Mercaptopurine [Purinethol tablet] &
149,DISEASE,0.999993,ALL,77.0,80.0,Treatment of adult and pediatric patients with...,60,normalize.disease.ncit:C3167,Acute Lymphoblastic Leukemia,Mercaptopurine [Purinethol tablet] &
150,DISEASE,0.999991,acute nonlymphocytic leukemias,61.0,91.0,Remission induction and remission consolidatio...,60,normalize.disease.ncit:C3171,Acute Myeloid Leukemia,Thioguanine [Tabloid]

In [12]:
# find preprocessing tool for pluralization, etc?
results[0:50]

,entity_group,score,word,start,end,original_text,concept_match_type,concept_id,concept_label,FDA Brand Label
0,GENETIC,0.999995,lysine methyltransferase 2A gene,58.0,90.0,Treatment of relapsed or refractory acute leuk...,0,None,None,Revumenib [Revuforj]
1,GENETIC,0.999970,KMT2A,92.0,97.0,Treatment of relapsed or refractory acute leuk...,100,normalize.gene.hgnc:7132,KMT2A,Revumenib [Revuforj]
2,CHEMICAL,0.999998,lysine,58.0,64.0,Treatment of relapsed or refractory acute leuk...,80,normalize.therapy.rxcui:6536,lysine,Revumenib [Revuforj]
3,DISEASE,0.999987,acute leukemia,36.0,50.0,Treatment of relapsed or refractory acute leuk...,80,normalize.disease.ncit:C9300,Acute Leukemia,Revumenib [Revuforj]
4,GENETIC,0.999995,isocitrate dehydrogenase - 1,126.0,152.0,Treatment of adult and pediatric patients 12 y...,0,None,None,Vorasidenib [Voranigo]
5,GENETIC,0.999984,IDH1,154.0,158.0,Treatment of adult and pediatric patients 12 y...,100,normalize.gene.hgnc:5382,IDH1,Vorasidenib [Voranigo]
6,GENETIC,0.999995,isocitrate dehydrogenase - 2,163.0,189.0,Treatment of adult and pediatric patients 12 y...,0,None,None,Vorasidenib [Voranigo]
7,GENETIC,0.999985,IDH2,191.0,195.0,Treatment of adult and pediatric patients 12 y...,100,normalize.gene.hgnc:5383,IDH2,Vorasidenib [Voranigo]
8,CHEMICAL,0.999998,isocitrate,126.0,136.0,Treatment of adult and pediatric patients 12 y...,80,normalize.therapy.chembl:CHEMBL539669,ISOCITRATE,Vorasidenib [Voranigo]
9,CHEMICAL,0.999998,isocitrate,163.0,173.0,Treatment of adult and pediatric patients 12 y...,80,normalize.therapy.chembl:CHEMBL539669,ISOCITRATE,Vorasidenib [Voranigo]
10,DISEASE,0.999994,astrocytoma,74.0,85.0,Treatment of adult and pediatric patients 12 y...,80,normalize.disease.ncit:C60781,Astrocytoma,Vorasidenib [Voranigo]
11,DISEASE,0.999991,oligodendroglioma,89.0,106.0,Treatment of adult and pediatric patients 12 y...,80,normalize.disease.ncit:C3288,Oligodendroglioma,Vorasidenib [Voranigo]
12,GENETIC,0.999950,CD19,13.0,17.0,Treatment of CD19-positive Philadelphia chromo...,100,normalize.gene.hgnc:1633,CD19,Blinatumomab [Blincyto]
13,DISEASE,0.999986,acute lymphoblastic leukemia,77.0,105.0,Treatment of CD19-positive Philadelphia chromo...,80,normalize.disease.ncit:C3167,Acute Lymphoblastic Leukemia,Blinatumomab [Blincyto]
14,DISEASE,0.999994,ALL,107.0,110.0,Treatment of CD19-positive Philadelphia chromo...,60,normalize.disease.ncit:C3167,Acute Lymphoblastic Leukemia,Blinatumomab [Blincyto]
15,GENETIC,0.999989,neurotrophic tyrosine receptor kinase,98.0,135.0,Treatment of adult and pediatric patients 12 y...,0,None,None,Repotrectinib [Augtyro]
16,GENETIC,0.999965,NTRK,137.0,141.0,Treatment of adult and pediatric patients 12 y...,0,None,None,Repotrectinib [Augtyro]
17,CHEMICAL,0.999998,tyrosine,111.0,119.0,Treatment of adult and pediatric patients 12 y...,80,normalize.therapy.rxcui:10962,tyrosine,Repotrectinib [Augtyro]
18,DISEASE,0.999954,tumors,79.0,85.0,Treatment of adult and pediatric patients 12 y...,60,normalize.disease.ncit:C3262,Neoplasm,Repotrectinib [Augtyro]
19,GENETIC,0.999987,RET gene fusion,123.0,138.0,Treatment of adult and pediatric patients 2 ye...,0,None,None,Selpercatinib [Retevmo]
20,DISEASE,0.999942,tumors,109.0,115.0,Treatment of adult and pediatric patients 2 ye...,60,normalize.disease.ncit:C3262,Neoplasm,Selpercatinib [Retevmo]
21,GENETIC,0.999987,RET gene fusion,117.0,132.0,Treatment of adult and pediatric patients 2 ye...,0,None,None,Selpercatinib [Retevmo]
22,CHEMICAL,0.999766,radioactive iodine,212.0,230.0,Treatment of adult and pediatric patients 2 ye...,0,None,None,Selpercatinib [Retevmo]
23,CHEMICAL,0.999855,radioactive iodine,246.0,264.0,Treatment of adult and pediatric patients 2 ye...,0,None,None,Selpercatinib [Retevmo]
24,DISEASE,0.999992,thyroid cancer,95.0,109.0,Treatment of adult and pediatric patients 2 ye...,80,normalize.disease.ncit:C7510,Malignant Thyroid Gland Neoplasm,Selpercatinib [Retevmo]
25,GENETIC,0.803028,RET mutation,133.0,145.0,Treatment of adult and pediatric patients 2 ye...,0,None,None,Selpercatinib [Retevmo]
26,DISEASE,0.999990,medullary thyroid cancer,95.0,119.0,Treatment of adult and pediatric patients 2 ye...,80,normalize.disease.ncit:C3879,Thyroid Gland Medullary Carcinoma,Selpercatinib [Retevmo]
27,DISEASE,0.999993,MTC,121.0,124.0,Treatment of adult and pediatric patients 2 ye...,60,normalize.disease.ncit:C3879,Thyroid Gland Medullary Carcinoma,Selpercatinib [Retevmo]
28,GENETIC,0.999992,somatostatin receptor,66.0,87.0,Treatment of adult and pediatric patients 12 y...,0,None,None,Lutetium Lu 177 dotatate [Lutathera]
29,CHEMICAL,0.999996,somatostatin,66.0,78.0,Treatment of adult and pediatric patients 12 y...,80,normalize.therapy.rxcui:9939,somatostatin,Lutetium Lu 177 dotatate [Lutathera]
30,DISEASE,0.999974,gastroenteropancreatic neuroendocrine tumors,97.0,141.0,Treatment of adult and pediatric patients 12 y...,60,normalize.disease.ncit:C95404,Digestive System Neuroendocrine Tumor,Lutetium Lu 177 dotatate [Lutathera]
31,DISEASE,0.999932,NETs,147.0,151.0,Treatment of adult and pediatric patients 12 y...,0,None,None,Lutetium Lu 177 dotatate [Lutathera]
32,DISEASE,0.999186,neuroendocrine tumors,193.0,214.0,Treatment of adult and pediatric patients 12 y...,80,normalize.disease.ncit:C3809,Neuroendocrine Neoplasm,Lutetium Lu 177 dotatate [Lutathera]
33,GENETIC,0.959270,BRAF fusion or,121.0,135.0,Treatment of patients 6 months of age and olde...,0,None,None,Tovorafenib [Ojemda]
34,GENETIC,0.999761,BRAF V600 mutation,154.0,172.0,Treatment of patients 6 months of age and olde...,0,None,None,Tovorafenib [Ojemda]
35,DISEASE,0.999952,low - grade glioma,86.0,102.0,Treatment of patients 6 months of age and olde...,0,None,None,Tovorafenib [Ojemda]
36,DISEASE,0.999989,LGG,104.0,107.0,Treatment of patients 6 months of age and olde...,60,normalize.disease.ncit:C132067,Low Grade Glioma,Tovorafenib [Ojemda]
37,GENETIC,0.999323,CD22,36.0,40.0,Treatment of relapsed or refractory CD22-posit...,100,normalize.gene.hgnc:1643,CD22,Inotuzumab ozogamicin [Besponsa]
38,DISEASE,0.999952,acute lymphoblastic leukemia,67.0,95.0,Treatment of relapsed or refractory CD22-posit...,80,normalize.disease.ncit:C3167,Acute Lymphoblastic Leukemia,Inotuzumab ozogamicin [Besponsa]
39,DISEASE,0.999993,ALL,97.0,100.0,Treatment of relapsed or refractory CD22-posit...,60,normalize.disease.ncit:C3167,Acute Lymphoblastic Leukemia,Inotuzumab ozogamicin [Besponsa]
40,GENETIC,0.999991,anti - GD2,201.0,209.0,To reduce the risk of relapse in adult and ped...,0,None,None,Eflornithine [Iwilfin]
41,DISEASE,0.987620,neuroblastoma,77.0,90.0,To reduce the risk of relapse in adult and ped...,80,normalize.disease.ncit:C3270,Neuroblastoma,Eflornithine [Iwilfin]
42,DISEASE,0.611234,HRNB,92.0,96.0,To reduce the risk of relapse in adult and ped...,0,None,None,Eflornithine [Iwilfin]
43,GENETIC,0.999991,neurotrophic tyrosine receptor kinase,91.0,128.0,Treatment of adult and pediatric patients olde...,0,None,None,Entrectinib [Rozlytrek]
44,GENETIC,0.999969,NTRK,130.0,134.0,Treatment of adult and pediatric patients olde...,0,None,None,Entrectinib [Rozlytrek]
45,CHEMICAL,0.999998,tyrosine,104.0,112.0,Treatment of adult and pediatric patients olde...,80,normalize.therapy.rxcui:10962,tyrosine,Entrectinib [Rozlytrek]
46,DISEASE,0.999983,tumors,72.0,78.0,Treatment of adult and pediatric patients olde...,60,normalize.disease.ncit:C3262,Neoplasm,Entrectinib [Rozlytrek]
47,DISEASE,0.999990,melanoma,140.0,148.0,Adjuvant treatment of adult and pediatric pati...,80,normalize.disease.ncit:C3224,Melanoma,Nivolumab [Opdivo]
48,DISEASE,0.999989,chronic myelogenous leukemia,123.0,151.0,Treatment of adult and pediatric patients 1 ye...,80,normalize.disease.ncit:C3174,"Chronic Myeloid Leukemia, BCR-ABL1 Positive",Bosutinib [Bosulif]
49,DISEASE,0.999991,CML,157.0,160.0,Treatment of adult and pediatric patients 1 ye...,60,normalize.disease.ncit:C3174,"Chronic Myeloid Leukemia, BCR-ABL1 Positive",Bosutinib [Bosulif]

In [13]:
# import inflect

# inflector = inflect.engine()

# def singularize(word):
#     return inflector.singular_noun(word) or word

# results['inflect_test'] = results['word'].apply(singularize)
# results[['word','inflect_test']][0:50]

In [11]:
import pandas as pd

condensed_results = tdf.groupby('FDA Brand Label').apply(
    lambda group: pd.Series({
        'GENETIC_LABELS': ' | '.join(group.loc[group['entity_group'] == 'GENETIC', 'concept_label'].unique()),
        'DISEASE_LABELS': ' | '.join(group.loc[group['entity_group'] == 'DISEASE', 'concept_label'].unique())
    })
).reset_index()
condensed_results

/var/folders/5t/sfw5tjx56m10xb861_pd3wfm0000gq/T/ipykernel_73837/1740886530.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  condensed_results = tdf.groupby('FDA Brand Label').apply(

,FDA Brand Label,GENETIC_LABELS,DISEASE_LABELS
0,Arsenic trioxide [Trisenox],PML,Acute Promyelocytic Leukemia with t(15;17)(q24...
1,Asparaginase Erwinia Chrysanthemi [Erwinaze] [...,,Acute Lymphoblastic Leukemia | Hypersensitivity
2,Asparaginase Erwinia chrysanthemi (recombinant...,,Acute Lymphoblastic Leukemia | Lymphoblastic L...
3,Asparaginase [Elspar],,Acute Lymphoblastic Leukemia
4,Atezolizumab [Tecentriq],,Alveolar Soft Part Sarcoma
5,Avelumab [Bavencio],,Merkel Cell Carcinoma
6,Azacitidine [Vidaza],,Juvenile Myelomonocytic Leukemia
7,Blinatumomab [Blincyto],CD19,Acute Lymphoblastic Leukemia
8,Bosutinib [Bosulif],,"Chronic Myeloid Leukemia, BCR-ABL1 Positive"
9,Brentuximab vedotin [Adcetris],,Hodgkin Lymphoma | Classic Hodgkin Lymphoma
10,Busulfan [Busulfex],,"Chronic Myeloid Leukemia, BCR-ABL1 Positive"
11,Cabozantinib [Cabometyx],KDR,Differentiated Thyroid Gland Carcinoma
12,Calaspargase pegol - mknl [Asparlas],,Acute Lymphoblastic Leukemia
13,Clofarabine [Clolar],,Acute Lymphoblastic Leukemia
14,Crizotinib [Xalkori],ALK,Inflammatory Myofibroblastic Tumor | Systemic ...
15,Cytarabine,,Malignant Neoplasm
16,Dabrafenib [Tafinlar],,Neoplasm | Low Grade Glioma
17,Dactinomycin [Cosmegen],,Wilms Tumor | Rhabdomyosarcoma | Ewing Sarcoma...
18,Dasatinib [Sprycel],,Acute Lymphoblastic Leukemia | Chronic Myeloid...
19,Daunorubicin Hydrochloride,,Acute Lymphoblastic Leukemia
20,Daunorubicin and cytarabine liposome [Vyxeos],,Acute Myeloid Leukemia | Myelodysplastic Syndrome
21,Dinutuximab [Unituxin],,Neuroblastoma
22,Eflornithine [Iwilfin],,Neuroblastoma
23,Emapalumab-lzsg [Gamifant],,Hemophagocytic Lymphohistiocytosis
24,Entrectinib [Rozlytrek],,Neoplasm
25,Everolimus [Afinitor] &,,Tuberous Sclerosis | Subependymal Giant Cell A...
26,Gemtuzumab ozogamicin [Mylotarg],CD33,Acute Myeloid Leukemia
27,Imatinib Mesylate [Gleevec] &,,Acute Lymphoblastic Leukemia | Chronic Myeloid...
28,Inotuzumab ozogamicin [Besponsa],CD22,Acute Lymphoblastic Leukemia
29,Iobenguane I-131 [Azedra],,pheochromocytoma | Paraganglioma
30,Ipilimumab [Yervoy],,Melanoma | Malignant Colorectal Neoplasm
31,Larotrectinib [Vitrakvi],,Neoplasm
32,Lomustine [Gleostine],,Brain Neoplasm
33,Lutetium Lu 177 dotatate [Lutathera],,Digestive System Neuroendocrine Tumor | Neuroe...
34,Mercaptopurine [Purinethol tablet] &,,Acute Lymphoblastic Leukemia
35,Methotrexate,,Acute Lymphoblastic Leukemia | Meningeal Leuke...
36,Naxitamab-gqgk [Danyelza],,Neuroblastoma
37,Nilotinib [Tasigna],,"Chronic Myeloid Leukemia, BCR-ABL1 Positive"
38,Nivolumab [Opdivo],,Melanoma | Malignant Colorectal Neoplasm | Col...
39,Nivolumab and Relatlimab-rmbw) [Opdualag],,Melanoma
40,Pegaspargase [Oncaspar],,Acute Lymphoblastic Leukemia | Hypersensitivity
41,Pembrolizumab [Keytruda],,Melanoma | Hodgkin Lymphoma | Classic Hodgkin ...
42,Pralsetinib [Gavreto],RET,Thyroid Gland Medullary Carcinoma | Malignant ...
43,Repotrectinib [Augtyro],,Neoplasm
44,Revumenib [Revuforj],KMT2A,Acute Leukemia
45,Rituximab [Rituxan],MS4A1,Diffuse Large B-Cell Lymphoma | Burkitt Lymphoma
46,Selpercatinib [Retevmo],,Neoplasm | Malignant Thyroid Gland Neoplasm | ...
47,Selumetinib [Koselugo],,Neurofibromatosis Type 1 | Neurofibroma | Poik...
48,Tagraxofusp-erzs [Elzonris],,Blastic Plasmacytoid Dendritic Cell Neoplasm
49,Tazemetostat [Tazverik],,Epithelioid Sarcoma
50,Thioguanine [Tabloid],,Acute Myeloid Leukemia
51,Tisagenlecleucel [Kymriah],,Acute Lymphoblastic Leukemia
52,Tovorafenib [Ojemda],,Low Grade Glioma
53,Trametinib [Mekinist],,Neoplasm | Low Grade Glioma
54,Tretinoin [Vesanoid],PML,Acute Promyelocytic Leukemia with t(15;17)(q24...
55,Vinblastine sulfate,,Malignant Neoplasm | Langerhans Cell Histiocyt...
56,Vorasidenib [Voranigo],IDH1 | IDH2,Astrocytoma | Oligodendroglioma

In [15]:
{
    'Evidence Type': [],
    'Clinical Significance': [],
    'Evidence Strength': [],
    'Variation': [],
    'Variation Label': [],
    'Variation Origin': [],
    'Disease': [], # Results
    'Drug': [], # Results
    'Drug Interaction Type': [],
    'Source': [],
    'Source Version': [],
    'Evidence Description': [], # Results
}

{'Evidence Type': [],
 'Clinical Significance': [],
 'Evidence Strength': [],
 'Variation': [],
 'Variation Label': [],
 'Variation Origin': [],
 'Disease': [],
 'Drug': [],
 'Drug Interaction Type': [],
 'Source': [],
 'Source Version': [],
 'Evidence Description': []}

In [12]:
df = df.rename(columns={'DRUGS APPROVED FOR PEDIATRIC CANCERS [BRAND NAME] 1': 'FDA Brand Label'})
df

,FDA Brand Label,INDICATION 2,PEDIATRIC APPROVAL DATE 3*
0,Revumenib [Revuforj],Treatment of relapsed or refractory acute leuk...,11-15-2024
1,Vorasidenib [Voranigo],Treatment of adult and pediatric patients 12 y...,08-06-2024
2,Blinatumomab [Blincyto],Treatment of CD19-positive Philadelphia chromo...,06-14-2024
3,Repotrectinib [Augtyro],Treatment of adult and pediatric patients 12 y...,06-13-2024
4,Selpercatinib [Retevmo],Treatment of adult and pediatric patients 2 ye...,05-29-2024
...,...,...,...
86,Methotrexate,Treatment of adults and pediatric patients wit...,12-07-1953
87,Methotrexate,Treatment of adults and pediatric patients wit...,12-07-1953
88,Mercaptopurine [Purinethol tablet] &,Treatment of adult and pediatric patients with...,09-11-1953
89,Thioguanine [Tabloid],Remission induction and remission consolidatio...,
90,Vincristine Sulfate,Acute leukemia; MULTIPLE (in combination),

In [13]:
results[results['FDA Brand Label'].str.contains('Pembrolizumab')]

,entity_group,score,word,start,end,original_text,concept_match_type,concept_id,concept_label,FDA Brand Label
82,DISEASE,0.999991,melanoma,100.0,108.0,Adjuvant treatment of adult and pediatric (12 ...,80,normalize.disease.ncit:C3224,Melanoma,Pembrolizumab [Keytruda]
120,DISEASE,0.999987,Hodgkin lymphoma,58.0,74.0,Treatment of pediatric patients with refractor...,80,normalize.disease.ncit:C9357,Hodgkin Lymphoma,Pembrolizumab [Keytruda]
121,DISEASE,0.999993,cHL,76.0,79.0,Treatment of pediatric patients with refractor...,60,normalize.disease.ncit:C7164,Classic Hodgkin Lymphoma,Pembrolizumab [Keytruda]
122,DISEASE,0.999993,cHL,85.0,88.0,Treatment of pediatric patients with refractor...,60,normalize.disease.ncit:C7164,Classic Hodgkin Lymphoma,Pembrolizumab [Keytruda]
125,DISEASE,0.999985,tumor,74.0,79.0,Treatment of adult and pediatric patients with...,60,normalize.disease.ncit:C3262,Neoplasm,Pembrolizumab [Keytruda]
126,DISEASE,0.999948,tumors,151.0,157.0,Treatment of adult and pediatric patients with...,60,normalize.disease.ncit:C3262,Neoplasm,Pembrolizumab [Keytruda]
136,DISEASE,0.999992,Merkel cell carcinoma,88.0,109.0,Treatment of adult and pediatric patients with...,80,normalize.disease.ncit:C9231,Merkel Cell Carcinoma,Pembrolizumab [Keytruda]
137,DISEASE,0.999989,MCC,111.0,114.0,Treatment of adult and pediatric patients with...,60,normalize.disease.ncit:C9231,Merkel Cell Carcinoma,Pembrolizumab [Keytruda]
158,DISEASE,0.897375,B - Cell lymphoma,84.0,99.0,Treatment of adult and pediatric patients with...,0,None,None,Pembrolizumab [Keytruda]
159,DISEASE,0.999976,PMBCL,101.0,106.0,Treatment of adult and pediatric patients with...,0,None,None,Pembrolizumab [Keytruda]
178,DISEASE,0.999976,tumors,157.0,163.0,Treatment of adult and pediatric patients with...,60,normalize.disease.ncit:C3262,Neoplasm,Pembrolizumab [Keytruda]

In [ ]:
merged_df = pd.merge(df, condensed_results, on='FDA Brand Label', how='left')
# merged_df.to_excel('tagged-dataset-joined.xlsx')
merged_df

,FDA Brand Label,INDICATION 2,PEDIATRIC APPROVAL DATE 3*,GENETIC_LABELS,DISEASE_LABELS
0,Revumenib [Revuforj],Treatment of relapsed or refractory acute leuk...,11-15-2024,KMT2A,Acute Leukemia
1,Vorasidenib [Voranigo],Treatment of adult and pediatric patients 12 y...,08-06-2024,IDH1 | IDH2,Astrocytoma | Oligodendroglioma
2,Blinatumomab [Blincyto],Treatment of CD19-positive Philadelphia chromo...,06-14-2024,CD19,Acute Lymphoblastic Leukemia
3,Repotrectinib [Augtyro],Treatment of adult and pediatric patients 12 y...,06-13-2024,,Neoplasm
4,Selpercatinib [Retevmo],Treatment of adult and pediatric patients 2 ye...,05-29-2024,,Neoplasm | Malignant Thyroid Gland Neoplasm | ...
...,...,...,...,...,...
86,Methotrexate,Treatment of adults and pediatric patients wit...,12-07-1953,,Acute Lymphoblastic Leukemia | Meningeal Leuke...
87,Methotrexate,Treatment of adults and pediatric patients wit...,12-07-1953,,Acute Lymphoblastic Leukemia | Meningeal Leuke...
88,Mercaptopurine [Purinethol tablet] &,Treatment of adult and pediatric patients with...,09-11-1953,,Acute Lymphoblastic Leukemia
89,Thioguanine [Tabloid],Remission induction and remission consolidatio...,,,Acute Myeloid Leukemia
90,Vincristine Sulfate,Acute leukemia; MULTIPLE (in combination),,NaN,NaN